import { layout, solwear } from "@solwear/sdk";
const hours=document.querySelector<HTMLElement>("#hours")!;const minutes=document.querySelector<HTMLElement>("#minutes")!;const seconds=document.querySelector<HTMLElement>("#seconds")!;const date=document.querySelector<HTMLElement>("#date")!;const battery=document.querySelector<HTMLElement>("#battery")!;const steps=document.querySelector<HTMLElement>("#steps")!;const greeting=document.querySelector<HTMLElement>("#greeting")!;const faceName=document.querySelector<HTMLElement>("#face-name")!;const walletKey=document.querySelector<HTMLElement>("#wallet-key")!;const dots=document.querySelector<HTMLElement>("#face-dots")!;
const pad=(n:number)=>String(n).padStart(2,"0");
const names=["GM","GN","DIGITAL","ANALOG","WALLET","MINIMAL"];
let face=Number(localStorage.getItem("solwear.face")??"0")%names.length;
function setFace(next:number){face=(next+names.length)%names.length;document.body.dataset.face=String(face);faceName.textContent=names[face];greeting.textContent=face===1?"GN":"GM";localStorage.setItem("solwear.face",String(face));dots.replaceChildren(...names.map((_,i)=>{const dot=document.createElement("i");if(i===face)dot.className="active";return dot;}));}
function paint(epochMs=Date.now()){const now=new Date(epochMs);const h=now.getHours();const m=now.getMinutes();const s=now.getSeconds();hours.textContent=pad(h);minutes.textContent=pad(m);seconds.textContent=pad(s);date.textContent=now.toLocaleDateString(undefined,{weekday:"short",month:"short",day:"numeric"}).toUpperCase();document.documentElement.style.setProperty("--hour-turn",`${((h%12)+m/60)/12}turn`);document.documentElement.style.setProperty("--minute-turn",`${(m+s/60)/60}turn`);document.documentElement.style.setProperty("--second-turn",`${s/60}turn`);}
async function refresh(){try{const [power,step]=await Promise.all([solwear.power.status(),solwear.sensors.read("steps")]);battery.textContent=`${power.percent}%${power.charging?" ⚡":""}`;steps.textContent=`${Math.round(step.value).toLocaleString()} steps`;}catch{battery.textContent="--%";}}
async function start(){await solwear.ready();layout(solwear.system.screen);setFace(face);paint();try{const key=await solwear.wallet.publicKey();walletKey.textContent=`${key.slice(0,6)}…${key.slice(-6)}`;}catch{walletKey.textContent="wallet locked";}solwear.on("tick",(tick)=>paint(tick.epochMs));solwear.on("button",(event)=>{if(event.action==="press")setFace(face+(event.button==="back"?-1:1));});document.body.addEventListener("click",()=>setFace(face+1));await refresh();setInterval(refresh,30_000);}
void start();
