import { layout, solwear } from "@solwear/sdk";
type Game="pong"|"tetris"|"pet";
const $=(id:string)=>document.getElementById(id)!;const menu=$("menu");const stage=$("stage");const score=$("score");let game:Game|null=null;let timer=0;let points=0;let paddle=38;let ball={x:48,y:30,dx:2.1,dy:2.5};const cells:boolean[]=Array(96).fill(false);let hunger=Number(localStorage.getItem("solwear.pet.hunger")??75);let happy=Number(localStorage.getItem("solwear.pet.happy")??70);
function open(next:Game){game=next;menu.hidden=true;stage.hidden=false;for(const id of ["pong","tetris","pet"])$(id).classList.toggle("active",id===next);points=0;score.textContent=next.toUpperCase();window.clearInterval(timer);if(next==="pong")timer=window.setInterval(tickPong,35);if(next==="tetris"){drawBoard();timer=window.setInterval(tickTetris,450);}if(next==="pet")drawPet();}
function close(){window.clearInterval(timer);game=null;menu.hidden=false;stage.hidden=true;score.textContent="SELECT";}
function action(){if(game==="pong")paddle=paddle<45?68:8;if(game==="tetris"){points++;cells[Math.floor(Math.random()*cells.length)]=true;drawBoard();}if(game==="pet")happy=Math.min(100,happy+4);}
function tickPong(){ball.x+=ball.dx;ball.y+=ball.dy;if(ball.x<2||ball.x>94)ball.dx*=-1;if(ball.y<2)ball.dy=Math.abs(ball.dy);if(ball.y>88){if(ball.x>paddle-6&&ball.x<paddle+30){ball.dy=-Math.abs(ball.dy);points++;score.textContent=`${points} PTS`;}else{ball={x:48,y:30,dx:2.1,dy:2.5};points=0;score.textContent="MISS";}}const view=$("pong");(view.querySelector(".ball") as HTMLElement).style.cssText=`left:${ball.x}%;top:${ball.y}%`;(view.querySelector(".paddle") as HTMLElement).style.left=`${paddle}%`;}
function tickTetris(){for(let row=11;row>0;row--)for(let col=0;col<8;col++)if(cells[(row-1)*8+col]&&!cells[row*8+col]){cells[row*8+col]=true;cells[(row-1)*8+col]=false;}if(Math.random()>.45)cells[Math.floor(Math.random()*8)]=true;const full=Array.from({length:12},(_,r)=>cells.slice(r*8,r*8+8).every(Boolean));full.forEach((yes,r)=>{if(yes){cells.splice(r*8,8);cells.unshift(...Array(8).fill(false));points+=10;}});score.textContent=`${points} PTS`;drawBoard();}
function drawBoard(){const board=$("board");if(!board.children.length)board.replaceChildren(...cells.map(()=>document.createElement("i")));Array.from(board.children).forEach((cell,i)=>cell.classList.toggle("on",cells[i]));}
function drawPet(){($("hunger") as HTMLMeterElement).value=hunger;($("happy") as HTMLMeterElement).value=happy;localStorage.setItem("solwear.pet.hunger",String(hunger));localStorage.setItem("solwear.pet.happy",String(happy));score.textContent=hunger>25&&happy>25?"SOL IS HAPPY":"SOL NEEDS YOU";}
menu.querySelectorAll<HTMLButtonElement>("button[data-game]").forEach(button=>button.onclick=()=>open(button.dataset.game as Game));$("back").onclick=close;$("pong").onclick=action;$("tetris").onclick=action;$("feed").onclick=()=>{hunger=Math.min(100,hunger+18);drawPet();};$("play").onclick=()=>{happy=Math.min(100,happy+15);hunger=Math.max(0,hunger-4);drawPet();};
async function start(){await solwear.ready();layout(solwear.system.screen);solwear.on("button",event=>{if(event.action!=="press")return;if(event.button==="back")close();else action();});setInterval(()=>{hunger=Math.max(0,hunger-1);happy=Math.max(0,happy-1);if(game==="pet")drawPet();},60_000);}
void start();
